### ISSUE TITLE
Asking for code

### ISSUE THREAD

**Issue by JiaxiangYi96** [aleximmer/heteroscedastic-nn#1]
Hello Alexander,

I am really interested in you research about Bayesian heteroscedastic regression, which is an excellent work. I am wondering when are you planning your code regarding this work?

Best wishes,

Jiaxiang Yi

**Comment by aleximmer** [comment]
Hi Jiaxiang, 

Thanks for your interest. The code will be made available this week. Sorry for the delay!

**Comment by aleximmer** [comment]
The code is now uploaded.
